package Ventanas;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Clases.Building;

/**
 *
 * @author AA
 */
public class MainView extends javax.swing.JFrame {
    DefaultTableModel modelObj;
    ArrayList<Building>buildingList;
    Building buildObj = new Building(0.1, 0.2, 0.3, 0.4, "Nothing", 0, "Empty", "Null");

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        ImageIcon imgObj = new ImageIcon("src/Img/ban.jpg");
        Icon oIcon = new ImageIcon(imgObj.getImage().getScaledInstance(lblPortada.getWidth(), lblPortada.getHeight(), Image.SCALE_DEFAULT));
        lblPortada.setIcon(oIcon);
        lblPortada1.setIcon(oIcon);
        this.MainTabbedPane.setSelectedIndex(0);
        this.modelObj = (DefaultTableModel) this.jTable1.getModel();
        this.buildingList = new ArrayList<>();
    }
    
    
    public void BuildList(){
        this.buildingList.add(new Building(buildObj.AreaBuilding(Double.parseDouble(this.txtAncho.getText()), Double.parseDouble(this.txtLargo.getText())),
        buildObj.HeightBuilding(buildObj.AreaBuilding(Double.parseDouble(this.txtAncho.getText()), Double.parseDouble(this.txtLargo.getText())), Double.parseDouble(this.txtAncho.getText())),
        buildObj.PerimeterBuilding(Double.parseDouble(this.txtPrimerLado.getText()), Double.parseDouble(this.txtSegundoLado.getText()), Double.parseDouble(this.txtTercerLado.getText()), Double.parseDouble(this.txtCuartoLado.getText())),
        buildObj.ScaleBuilding(Double.parseDouble(this.txtEscalaTerreno.getText())), this.jComboBox1.getSelectedItem().toString(), Integer.parseInt(this.txtNPisos.getText()), this.txtUsuario.getText(),
        this.lblNOMBREARQUI.getText()));
    }
    
    
    public void BuildArchitect(){
        String buildingTypeOBJ = this.jComboBox1.getSelectedItem().toString().toLowerCase();
            switch (buildingTypeOBJ) {
                case "hospitalario":
                    this.lblNOMBREARQUI.setText("Frank Owen Gehry");
                    break;
                case "polideportivo":
                   this.lblNOMBREARQUI.setText("Richard Meier");
                    break;    
                default:
                    this.lblNOMBREARQUI.setText("Antoni Gaudí");
                    break;
            }
    }
    
    
    public void DrawTable(){
        this.modelObj.getDataVector().removeAllElements();
        this.modelObj.fireTableDataChanged();
            for (int i = 0; i < buildingList.size(); i++) {
                String[] data = {
                 this.buildingList.get(i).GetCostumer(), this.buildingList.get(i).GetBuildingType(), Double.toString(this.buildingList.get(i).GetArea()),
                 Double.toString(this.buildingList.get(i).GetPerimeter()), Double.toString(this.buildingList.get(i).GetHeight()), Double.toString(this.buildingList.get(i).GetScale()), this.buildingList.get(i).Date(),
                 this.buildingList.get(i).GetArchitect()
                };
                this.modelObj.addRow(data);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        jPanConstruccion = new javax.swing.JPanel();
        jPanPortada = new javax.swing.JPanel();
        lblPortada1 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        jPanInfoTerreno = new javax.swing.JPanel();
        lblDATOSALLENAR = new javax.swing.JLabel();
        lblPRIMER = new javax.swing.JLabel();
        lblSEGUNDO = new javax.swing.JLabel();
        lblTERCER = new javax.swing.JLabel();
        lblCUARTO = new javax.swing.JLabel();
        txtTercerLado = new javax.swing.JTextField();
        txtPrimerLado = new javax.swing.JTextField();
        txtSegundoLado = new javax.swing.JTextField();
        txtCuartoLado = new javax.swing.JTextField();
        lblESCALADELTERR = new javax.swing.JLabel();
        txtEscalaTerreno = new javax.swing.JTextField();
        jPanInfoEdificio = new javax.swing.JPanel();
        lblUSUARIO = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblTIPOCONSTRUC = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblARQUITECTO = new javax.swing.JLabel();
        lblEMPRESASOLICITA = new javax.swing.JLabel();
        txtEmpresaSolicita = new javax.swing.JTextField();
        lblNOMBREARQUI = new javax.swing.JLabel();
        lblNPISOS = new javax.swing.JLabel();
        txtNPisos = new javax.swing.JTextField();
        lblAGREGARASCENSOR = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanCrear = new javax.swing.JPanel();
        lblDATOSALLENARXD = new javax.swing.JLabel();
        lblANCHO = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        lblLARGO = new javax.swing.JLabel();
        txtLargo = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jPanMostrar = new javax.swing.JPanel();
        lblCREDITOS = new javax.swing.JLabel();
        jPanTab = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        lblARCHI = new javax.swing.JLabel();
        lblARCHI1 = new javax.swing.JLabel();
        lblARCHI2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a NVIDIA: Architect Enterprise");

        MainTabbedPane.setBackground(new java.awt.Color(255, 0, 0));
        MainTabbedPane.setBorder(new javax.swing.border.MatteBorder(null));
        MainTabbedPane.setForeground(new java.awt.Color(0, 204, 0));
        MainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        MainTabbedPane.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        MainTabbedPane.setName(""); // NOI18N

        lblPortada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ban.jpg"))); // NOI18N

        lblTitulo1.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblTitulo1.setText("ARCHITECT ENTERPRISE");

        lblTitulo2.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(0, 153, 0));
        lblTitulo2.setText("ARCHITECT ENTERPRISE");

        lblTitulo3.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo3.setText("ARCHITECT ENTERPRISE");

        javax.swing.GroupLayout jPanPortadaLayout = new javax.swing.GroupLayout(jPanPortada);
        jPanPortada.setLayout(jPanPortadaLayout);
        jPanPortadaLayout.setHorizontalGroup(
            jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanPortadaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPortada1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitulo2)
                        .addComponent(lblTitulo1)
                        .addComponent(lblTitulo3))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanPortadaLayout.setVerticalGroup(
            jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanPortadaLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanPortadaLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(lblTitulo2))
                        .addComponent(lblTitulo1)
                        .addGroup(jPanPortadaLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(lblTitulo3)))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanPortadaLayout.createSequentialGroup()
                    .addComponent(lblPortada1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanInfoTerreno.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del terreno"));
        jPanInfoTerreno.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jPanInfoTerreno.setName("Terreno"); // NOI18N

        lblDATOSALLENAR.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblDATOSALLENAR.setText("(Datos a llenar: completar en metros, terreno cuadrado)");

        lblPRIMER.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblPRIMER.setText("Primer lado:");

        lblSEGUNDO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblSEGUNDO.setText("Segundo lado:");

        lblTERCER.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblTERCER.setText("Tercer lado:");

        lblCUARTO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblCUARTO.setText("Cuarto lado:");

        txtTercerLado.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtTercerLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTercerLadoKeyTyped(evt);
            }
        });

        txtPrimerLado.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtPrimerLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimerLadoKeyTyped(evt);
            }
        });

        txtSegundoLado.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtSegundoLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundoLadoKeyTyped(evt);
            }
        });

        txtCuartoLado.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtCuartoLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuartoLadoKeyTyped(evt);
            }
        });

        lblESCALADELTERR.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblESCALADELTERR.setText("Escala del terreno:");

        txtEscalaTerreno.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtEscalaTerreno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEscalaTerrenoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanInfoTerrenoLayout = new javax.swing.GroupLayout(jPanInfoTerreno);
        jPanInfoTerreno.setLayout(jPanInfoTerrenoLayout);
        jPanInfoTerrenoLayout.setHorizontalGroup(
            jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDATOSALLENAR)
                    .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                        .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                                .addComponent(lblPRIMER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrimerLado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                                .addComponent(lblTERCER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTercerLado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                                .addComponent(lblSEGUNDO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSegundoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                                .addComponent(lblCUARTO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCuartoLado))))
                    .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                        .addComponent(lblESCALADELTERR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEscalaTerreno)))
                .addGap(18, 18, 18))
        );
        jPanInfoTerrenoLayout.setVerticalGroup(
            jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoTerrenoLayout.createSequentialGroup()
                .addComponent(lblDATOSALLENAR)
                .addGap(18, 18, 18)
                .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRIMER)
                    .addComponent(lblSEGUNDO)
                    .addComponent(txtPrimerLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegundoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTERCER)
                    .addComponent(lblCUARTO)
                    .addComponent(txtTercerLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuartoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanInfoTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblESCALADELTERR)
                    .addComponent(txtEscalaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanInfoEdificio.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del edificio a construir"));
        jPanInfoEdificio.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jPanInfoEdificio.setName("Edificio"); // NOI18N

        lblUSUARIO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblUSUARIO.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        lblTIPOCONSTRUC.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblTIPOCONSTRUC.setText("Tipo de contrucción:");

        jComboBox1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polideportivo", "Hospitalario", "Educativo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblARQUITECTO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblARQUITECTO.setText("Arquitecto:");

        lblEMPRESASOLICITA.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblEMPRESASOLICITA.setText("Empresa solicitadora:");

        txtEmpresaSolicita.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtEmpresaSolicita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpresaSolicitaKeyTyped(evt);
            }
        });

        lblNOMBREARQUI.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        lblNPISOS.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblNPISOS.setText("Número de pisos:");

        txtNPisos.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtNPisos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPisosKeyTyped(evt);
            }
        });

        lblAGREGARASCENSOR.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblAGREGARASCENSOR.setText("¿Agregar ascensor?");

        jCheckBox1.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jCheckBox1.setText("Sí");

        javax.swing.GroupLayout jPanInfoEdificioLayout = new javax.swing.GroupLayout(jPanInfoEdificio);
        jPanInfoEdificio.setLayout(jPanInfoEdificioLayout);
        jPanInfoEdificioLayout.setHorizontalGroup(
            jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                        .addComponent(lblEMPRESASOLICITA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresaSolicita))
                    .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                        .addComponent(lblTIPOCONSTRUC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                        .addComponent(lblARQUITECTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNOMBREARQUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                        .addComponent(lblNPISOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNPisos))
                    .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                        .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                                .addComponent(lblAGREGARASCENSOR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1))
                            .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                                .addComponent(lblUSUARIO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanInfoEdificioLayout.setVerticalGroup(
            jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanInfoEdificioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUSUARIO)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEMPRESASOLICITA)
                    .addComponent(txtEmpresaSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTIPOCONSTRUC)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblARQUITECTO, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(lblNOMBREARQUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNPISOS)
                    .addComponent(txtNPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanInfoEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAGREGARASCENSOR)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 51, 51), null));

        lblDATOSALLENARXD.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblDATOSALLENARXD.setText("<html>(Datos a llenar: completar en metros, <br>\nedificio rectángular)</html>");

        lblANCHO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblANCHO.setText("Ancho:");

        txtAncho.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtAncho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchoKeyTyped(evt);
            }
        });

        lblLARGO.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblLARGO.setText("Largo:");

        txtLargo.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        txtLargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLargoKeyTyped(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnCreate.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 0));
        btnCreate.setText("CREAR CONSTRUCCIÓN");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanCrearLayout = new javax.swing.GroupLayout(jPanCrear);
        jPanCrear.setLayout(jPanCrearLayout);
        jPanCrearLayout.setHorizontalGroup(
            jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanCrearLayout.createSequentialGroup()
                                .addComponent(lblLARGO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLargo))
                            .addGroup(jPanCrearLayout.createSequentialGroup()
                                .addComponent(lblANCHO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(173, 173, 173))
                    .addGroup(jPanCrearLayout.createSequentialGroup()
                        .addGroup(jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDATOSALLENARXD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanCrearLayout.setVerticalGroup(
            jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDATOSALLENARXD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblANCHO)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLARGO)
                    .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanConstruccionLayout = new javax.swing.GroupLayout(jPanConstruccion);
        jPanConstruccion.setLayout(jPanConstruccionLayout);
        jPanConstruccionLayout.setHorizontalGroup(
            jPanConstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanConstruccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanInfoTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanInfoEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanConstruccionLayout.setVerticalGroup(
            jPanConstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanConstruccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanConstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanInfoTerreno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanInfoEdificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanConstruccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanInfoTerreno.getAccessibleContext().setAccessibleName("Información del terreno");
        jPanInfoEdificio.getAccessibleContext().setAccessibleName("Información del edificio a contruir");

        MainTabbedPane.addTab("CREAR CONSTRUCCIÓN", jPanConstruccion);

        lblCREDITOS.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        lblCREDITOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCREDITOS.setText("<html>Nvidia ARCHITECT ENTERPRISE, somos una empresa de Ingenieros y Arquitectos con visión y presencia regional, conformada por profesionales altamente calificados,<br>\ncon calidad humana, valores éticos y cristianos, cada uno con alto sentido de servicio al cliente y enfocados a obtener grandes resultados a través de la buena<br>\nadministración de los recursos, con estándares de calidad que garantizan la satisfacción de los clientes.</html>");

        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ban.jpg"))); // NOI18N

        lblARCHI.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblARCHI.setForeground(new java.awt.Color(0, 153, 0));
        lblARCHI.setText("ARCHITECT ENTERPRISE");

        lblARCHI1.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblARCHI1.setText("ARCHITECT ENTERPRISE");

        lblARCHI2.setFont(new java.awt.Font("Lucida Console", 1, 60)); // NOI18N
        lblARCHI2.setForeground(new java.awt.Color(153, 153, 153));
        lblARCHI2.setText("ARCHITECT ENTERPRISE");

        javax.swing.GroupLayout jPanTabLayout = new javax.swing.GroupLayout(jPanTab);
        jPanTab.setLayout(jPanTabLayout);
        jPanTabLayout.setHorizontalGroup(
            jPanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblARCHI)
                    .addComponent(lblARCHI1)
                    .addComponent(lblARCHI2)))
        );
        jPanTabLayout.setVerticalGroup(
            jPanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabLayout.createSequentialGroup()
                .addGroup(jPanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanTabLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanTabLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblARCHI))
                            .addComponent(lblARCHI1)
                            .addGroup(jPanTabLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblARCHI2))))
                    .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
        jTable1.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario/Cliente", "Tipo de construcción", "Área", "Perímetro", "Altura", "Escala", "Fecha", "Arquitecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanMostrarLayout = new javax.swing.GroupLayout(jPanMostrar);
        jPanMostrar.setLayout(jPanMostrarLayout);
        jPanMostrarLayout.setHorizontalGroup(
            jPanMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanMostrarLayout.createSequentialGroup()
                .addGroup(jPanMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanMostrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanMostrarLayout.createSequentialGroup()
                                .addComponent(jPanTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(lblCREDITOS)))
                    .addGroup(jPanMostrarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanMostrarLayout.setVerticalGroup(
            jPanMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanMostrarLayout.createSequentialGroup()
                .addComponent(jPanTab, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCREDITOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("MOSTRAR PROYECTO", jPanMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabbedPane)
        );

        MainTabbedPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char validate = evt.getKeyChar();
        if (Character.isDigit(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    
    private void txtEmpresaSolicitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpresaSolicitaKeyTyped
        char validate = evt.getKeyChar();
        if (Character.isDigit(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtEmpresaSolicitaKeyTyped

    
    private void txtNPisosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNPisosKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtNPisosKeyTyped

    
    private void txtPrimerLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerLadoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtPrimerLadoKeyTyped

    
    private void txtSegundoLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoLadoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtSegundoLadoKeyTyped

    
    private void txtTercerLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTercerLadoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtTercerLadoKeyTyped

    
    private void txtCuartoLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuartoLadoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtCuartoLadoKeyTyped

    
    private void txtEscalaTerrenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEscalaTerrenoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtEscalaTerrenoKeyTyped

    
    private void txtAnchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtAnchoKeyTyped

    
    private void txtLargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLargoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Tipo de dato NO VÁLIDO", "Validación: Error", 1);
        }
    }//GEN-LAST:event_txtLargoKeyTyped

    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        this.BuildArchitect();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       this.BuildList();
       this.DrawTable();
       this.MainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanConstruccion;
    private javax.swing.JPanel jPanCrear;
    private javax.swing.JPanel jPanInfoEdificio;
    private javax.swing.JPanel jPanInfoTerreno;
    private javax.swing.JPanel jPanMostrar;
    private javax.swing.JPanel jPanPortada;
    private javax.swing.JPanel jPanTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAGREGARASCENSOR;
    private javax.swing.JLabel lblANCHO;
    private javax.swing.JLabel lblARCHI;
    private javax.swing.JLabel lblARCHI1;
    private javax.swing.JLabel lblARCHI2;
    private javax.swing.JLabel lblARQUITECTO;
    private javax.swing.JLabel lblCREDITOS;
    private javax.swing.JLabel lblCUARTO;
    private javax.swing.JLabel lblDATOSALLENAR;
    private javax.swing.JLabel lblDATOSALLENARXD;
    private javax.swing.JLabel lblEMPRESASOLICITA;
    private javax.swing.JLabel lblESCALADELTERR;
    private javax.swing.JLabel lblLARGO;
    private javax.swing.JLabel lblNOMBREARQUI;
    private javax.swing.JLabel lblNPISOS;
    private javax.swing.JLabel lblPRIMER;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblPortada1;
    private javax.swing.JLabel lblSEGUNDO;
    private javax.swing.JLabel lblTERCER;
    private javax.swing.JLabel lblTIPOCONSTRUC;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblUSUARIO;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCuartoLado;
    private javax.swing.JTextField txtEmpresaSolicita;
    private javax.swing.JTextField txtEscalaTerreno;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtNPisos;
    private javax.swing.JTextField txtPrimerLado;
    private javax.swing.JTextField txtSegundoLado;
    private javax.swing.JTextField txtTercerLado;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
